const userH2 = document.getElementById("userH2");
const compH2= document.getElementById("compH2");
const imgRock=document.getElementById("imgRock");
const imgPaper=document.getElementById("imgPaper");
const imgScissors =document.getElementById("imgScissors");
const userPoint = document.getElementById("userPoint");
const compPoint =document.getElementById("compPoint")
const h3User= document.querySelector(".h3User");
const h3Comp = document.querySelector(".h3Comp");
const userImg=document.getElementById("userImg");
const compImg= document.getElementById("compImg")